import { useEffect, useState } from 'react';
import { Swords, Users, Map as MapIcon, Loader2 } from 'lucide-react';
import api from '../services/api';

export default function MatchLedger() {
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchMatches = async () => {
      try {
        const res = await api.get('/matches');
        setMatches(res.data);
      } catch (err) {
        console.error("Failed to fetch matches", err);
      } finally {
        setLoading(false);
      }
    };

    fetchMatches();
    // Poll every 5 seconds to catch new matches generated by the Auto-Tick engine
    const interval = setInterval(fetchMatches, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">Match Ledger</h1>
        <p className="text-zinc-400 text-sm mt-1">Immutable record of deployed engagements.</p>
      </header>

      {loading ? (
        <div className="flex justify-center py-20">
          <Loader2 className="animate-spin text-emerald-500" size={32} />
        </div>
      ) : matches.length === 0 ? (
        <div className="bg-[#0a0a0a] border border-white/5 p-10 rounded-2xl text-center text-zinc-500">
          No matches recorded in the database yet. Run the stress tester.
        </div>
      ) : (
        <div className="grid gap-4">
          {matches.map((match) => (
            <div key={match.match_id} className="bg-[#0a0a0a] border border-white/5 p-5 rounded-2xl flex items-center justify-between hover:border-white/10 transition-colors group">
              <div className="flex items-center gap-6">
                <div className="h-12 w-12 rounded-full bg-zinc-900 border border-white/5 flex items-center justify-center">
                  <Swords className={`transition-colors ${match.winner ? 'text-blue-500' : 'text-emerald-500 group-hover:text-emerald-400'}`} size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-medium tracking-tight text-white flex items-center gap-2">
                    Deployment {match.match_id.split('-')[0].toUpperCase()}
                    {!match.winner && <span className="bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-[10px] px-2 py-0.5 rounded-full">ACTIVE</span>}
                    {match.winner && <span className="bg-zinc-800 text-zinc-400 border border-zinc-700 text-[10px] px-2 py-0.5 rounded-full">RESOLVED: TEAM {match.winner}</span>}
                  </h3>
                  <div className="flex items-center gap-4 text-sm text-zinc-500 mt-1">
                    <span className="flex items-center gap-1"><MapIcon size={14}/> {match.map}</span>
                    <span className="flex items-center gap-1"><Users size={14}/> Avg Elo: {match.avg_elo}</span>
                  </div>
                </div>
              </div>
              
              <div className="text-right">
                <div className="text-xs font-mono text-zinc-500 bg-zinc-900 px-2 py-1 rounded">
                  TYPE: {match.match_type}
                </div>
                <div className="text-xs text-zinc-600 mt-2">
                  {new Date(match.created_at).toLocaleTimeString()}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}